url: "https://eunsoolee.co" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "/flowers_superpowers" # the subpath of your site, e.g. /blog
title: "Eunsoo Lee" # the name of your site, e.g. ACME Corp.
future: true
published: true